
export const states = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
    "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
    "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
    "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
    "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"
  ];

export const state_names = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY"
  }
  
export const locationOptions = [...states, ...Object.keys(state_names)];

const zipCodeToStateMap: { [zip: string]: string } = {
  "995": "AK",
  "850": "AZ",
  "722": "AR",
  "942": "CA",
  "802": "CO",
  "061": "CT",
  "199": "DE",
  "323": "FL",
  "303": "GA",
  "968": "HI",
  "832": "ID",
  "606": "IL",
  "462": "IN",
  "528": "IA",
  "666": "KS",
  "406": "KY",
  "708": "LA",
  "043": "ME",
  "214": "MD",
  "021": "MA",
  "024": "MA",
  "489": "MI",
  "551": "MN",
  "392": "MS",
  "651": "MO",
  "590": "MT",
  "685": "NE",
  "897": "NV",
  "033": "NH",
  "070": "NJ",
  "875": "NM",
  "100": "NY",
  "275": "NC",
  "585": "ND",
  "441": "OH",
  "731": "OK",
  "972": "OR",
  "171": "PA",
  "029": "RI",
  "292": "SC",
  "575": "SD",
  "372": "TN",
  "733": "TX",
  "841": "UT",
  "056": "VT",
  "232": "VA",
  "980": "WA",
  "253": "WV",
  "532": "WI",
  "820": "WY"
};

export function zipCodeState(zip: string): string {
  const prefix = zip.substring(0, 3);
  return zipCodeToStateMap[prefix] || "Unknown";
}
